kind: pipeline
type: docker
name: main

platform:
  arch: arm
  os: linux

steps:
  - name: debug
    image: alpine
    commands:
      - apk add curl jq
      - tag=$(curl -s https://api.github.com/repos/argoproj/argo-cd/tags | jq -crM 'map(select(.name | startswith("v")))[0].name')
      - sha=$(curl -s https://api.github.com/repos/argoproj/argo-cd/tags | jq -crM 'map(select(.name | startswith("v")))[0].commit.sha')
      - echo $tag
      - echo $sha
      - curl -s https://registry.hub.docker.com/v2/repositories/reireias/argocd/tags/ | jq -crM '.results[].name'
  - name: debug2
    image: plugins/docker
    commands:
      - echo $sha
