kind: pipeline
type: docker
name: main

platform:
  arch: arm
  os: linux

steps:
  - name: clone argo-cd
    image: docker
    commands:
      - apk add curl jq git
      - rm -rf .git
      - tag=$(curl -s https://api.github.com/repos/argoproj/argo-cd/tags | jq -crM 'map(select(.name | startswith("v")))[0].name')
      - sha=$(curl -s https://api.github.com/repos/argoproj/argo-cd/tags | jq -crM 'map(select(.name | startswith("v")))[0].commit.sha')
      - echo $tag
      - echo $sha
      - result=$(curl -s https://registry.hub.docker.com/v2/repositories/reireias/argocd/tags/ | jq -crM '.results[].name' | grep -q $tag; true)
      - |
        if [ -z "$result" ]; then
          git clone https://github.com/argoproj/argo-cd.git -b $tag
          mv -v argo-cd/* ./
          mv -v argo-cd/.[!.]* ./
          echo -n "latest,$tag" > .tags
        else
          # exit pipeline
          exit 78
        fi
  - name: image build
    image: plugins/docker
    settings:
      repo: reireias/argocd
      build_args:
        - BUILD_ALL_CLIS="false"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
