kind: pipeline
type: docker
name: main

platform:
  arch: arm
  os: linux

steps:
  - name: debug
    image: plugins/docker
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    commands:
      - apk add curl jq git
      - tag=$(curl -s https://api.github.com/repos/argoproj/argo-cd/tags | jq -crM 'map(select(.name | startswith("v")))[0].name')
      - sha=$(curl -s https://api.github.com/repos/argoproj/argo-cd/tags | jq -crM 'map(select(.name | startswith("v")))[0].commit.sha')
      - echo $tag
      - echo $sha
      - >
        curl -s https://registry.hub.docker.com/v2/repositories/reireias/argocd/tags/
        | jq -crM '.results[].name'
        | grep -q $tag
        || git clone https://github.com/argoproj/argo-cd.git -b $tag
        && cd argo-cd
        && docker login -u $USERNAME -p $PASSWORD
        && docker build -t reireias/argocd:$tag --build-arg BUILD_ALL_CLIS="false" .
        && docker tag reireias/argocd:$tag reireias/argocd:latest
        && docker push reireias/argocd:$tag
        && docker push reireias/argocd:latest
    volumes:
      - name: docker
        path: /var/run/docker.sock
